### ISSUE TITLE
parallax (iteration #2) feedback

### ISSUE THREAD

**Issue by romain-grecourt** [oracle/helidon-site#15]
This issue gathers the various feedback on the 2nd iteration of the landing page (parallax).

## Scenery

- The scenery for the parallax does not feel relevant to Helidon. Apart the developers using a laptop there isn't much to identify the site as "development framework", "cloud native java".

- It feels a little over-designed. The amount of detail creates some kind of heaviness.

- Some of the characters look like parent/child because of the size difference

- Depending on the scroll sensitivity of the mouse, it can take several turns of the mouse thumbwheel to get past the parallax content

## Mobile navigation

- The mobile navigation is not very practical. It takes several scrolls to get to the "features" screen. The first screen should be a little shorter so that users can get to the 2nd screen with a single scroll.

- The truncated scenery does not show much on certain devices (e.g. phones). It may be better to have fewer elements (e.g. sky, cloud, bird) ; this may help solving the scroll issue.

## Full screen effect

- The spacing between the screens feels a little like a zoomed-in effect.

**Comment by kumar-dhanagopal** [comment]
Just curious... I don't see the "parallax" scrolling effect -- i.e., foreground vs. background depth, differential motion, etc.  What am i missing?

**Comment by romain-grecourt** [comment]
> Just curious... I don't see the "parallax" scrolling effect -- i.e., foreground vs. background depth, differential motion, etc. What am i missing?

Make sure you refresh your cache and have a window width of ~1000px.

**Comment by romain-grecourt** [comment]
> Also, what was the motivation for the redesign - was there user feedback for example? On a related note, is our site set up to track web analytics ?

The previous site was temporary ; the parallax was targeted from the beginning.
